// Generated by CoffeeScript 1.8.0
(function(document) {
  if (document.question === "Client Registration") {
    return emit(document.Lastname, {
      last_name: document.Lastname,
      first_name: document.Firstname,
      other_names: document.Othernames,
      phone: document.Phonenumber,
      id: document._id
    });
  }
});

//# sourceMappingURL=map.js.map
