// Generated by CoffeeScript 1.8.0
var ClientSummaryView,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ClientSummaryView = (function(_super) {
  __extends(ClientSummaryView, _super);

  function ClientSummaryView() {
    this.renderResult = __bind(this.renderResult, this);
    this.render = __bind(this.render, this);
    this.changeQuestionSet = __bind(this.changeQuestionSet, this);
    this.startVisit = __bind(this.startVisit, this);
    this.editclientInfo = __bind(this.editclientInfo, this);
    return ClientSummaryView.__super__.constructor.apply(this, arguments);
  }

  ClientSummaryView.prototype.el = '#content';

  ClientSummaryView.prototype.events = {
    "click .startVisit": "startVisit",
    "click .editClientInfo": "editclientInfo"
  };

  ClientSummaryView.prototype.editclientInfo = function() {
    console.log('alskdfj');
    Coconut.menuView.renderForClientInfo(this.client);
    return document.location.href = "#edit/result/" + this.client.clientID;
  };

  ClientSummaryView.prototype.startVisit = function() {
    Coconut.menuView.renderForClientVisit(this.client);
    $("html, body").animate({
      scrollTop: $('#top-menu').offset().top
    });
    return document.location.href = "#new/result/Outpatient Visit/" + this.client.clientID;
  };

  ClientSummaryView.prototype.changeQuestionSet = function(newQuestionSet) {
    return document.location.href = newQuestionSet;
  };

  ClientSummaryView.prototype.render = function() {
    var data;
    console.log(this.client);
    Coconut.menuView.renderForClient(this.client);
    this.$el.html("<div class='aSection'> <table class='patientInfo'> <thead><th colspan='2' class = 'noteorhint'>Please check that this information is up to date</th></thead> <tbody> " + (data = {
      "Age": "Age",
      "Gender": "Gender",
      "Allergies": "Allergies",
      "Known Issues": "Known Issues",
      "Membership status": "Membership status"
    }, _.map(data, function(value, property) {
      return "<tr> <td> " + property + " </td> <td> " + value + " </td> </tr>";
    }).join("")) + " </tbody> <tfoot><th colspan='2'> <a class='buttonLinks editClientInfo' > Edit " + (this.client.firstName()) + "'s Info</a> </th></tfoot> </table> </div> <a class='buttonLinks startVisit' > New clinical visit for " + (this.client.firstName()) + "</a> <a class='buttonLinks startVisit' > Followup visit for " + (this.client.firstName()) + "</a> <div class='aSection'> <h2>Previous Visits/Forms</h2> " + (_.map(this.client.clientResultsSortedMostRecentFirst(), (function(_this) {
      return function(result, index) {
        var date, id, question;
        date = result.createdAt || result.VisitDate || result.fDate;
        question = result.question || result.source;
        id = result._id || "";
        return "<form class='previousVisitsList hideText'> <button class='fullwidthdropdown' onClick='$(\"#result-" + index + "\").slideToggle(1000)' type='button'>" + question + ": " + date + "</button> </form> <div id='result-" + index + "' class='aPreviousVisit' style='display: none'> " + (_this.renderResult(result)) + " " + (result.question != null ? "<form class='hideText' method='get' action='#edit/result/" + id + "'> <button>Edit</button> </form>" : "") + " </div>";
      };
    })(this)).join("")) + " </div>");
    return $("button").button();
  };

  ClientSummaryView.prototype.renderResult = function(result) {
    return "<table class='lastVisitResults'> <thead> <th>Property</th> <th>Value</th> </thead> <tbody> " + (_.map(result, function(value, property) {
      return "<tr> <td> " + property + " </td> <td> " + value + " </td> </tr>";
    }).join("")) + " <tr> </tr> </tbody> </table>";
  };

  return ClientSummaryView;

})(Backbone.View);

//# sourceMappingURL=ClientSummary.js.map
