// Generated by CoffeeScript 1.8.0
var LegacyInputView,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

LegacyInputView = (function(_super) {
  __extends(LegacyInputView, _super);

  function LegacyInputView() {
    this.render = __bind(this.render, this);
    return LegacyInputView.__super__.constructor.apply(this, arguments);
  }

  LegacyInputView.prototype.el = '#constantbuttons';

  LegacyInputView.prototype.events = {
    "click #addNewRecord": "addRecord"
  };

  LegacyInputView.prototype.render = function() {
    return this.$el.html("<button id='addNewRecord' type='button'>Add New Legacy Record</button>");
  };

  LegacyInputView.prototype.addRecord = function() {
    var burgerbutton, lastName, menu;
    lastName = "skdfj";
    Coconut.router.navigate("/new/result/Legacy Input/" + lastName, true);
    $("html, body").animate({
      scrollTop: $('#top-menu').offset().top
    });
    menu = $('.main-nav');
    burgerbutton = $('.menuburger');
    menu.removeClass("open");
    menu.css('display', 'none');
    return burgerbutton.removeClass("menuisopen", "slow");
  };

  return LegacyInputView;

})(Backbone.View);

//# sourceMappingURL=LegacyInputView.js.map
