// Generated by CoffeeScript 1.8.0
var QuestionView,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

window.SkipTheseWhen = function(argQuestions, result) {
  var disabledClass, question, questions, _i, _j, _len, _len1, _results;
  questions = [];
  argQuestions = argQuestions.split(/\s*,\s*/);
  for (_i = 0, _len = argQuestions.length; _i < _len; _i++) {
    question = argQuestions[_i];
    questions.push(window.questionCache[question]);
  }
  disabledClass = "disabled_skipped";
  _results = [];
  for (_j = 0, _len1 = questions.length; _j < _len1; _j++) {
    question = questions[_j];
    if (result) {
      _results.push(question.addClass(disabledClass));
    } else {
      _results.push(question.removeClass(disabledClass));
    }
  }
  return _results;
};

window.ResultOfQuestion = function(name) {
  var _base;
  return (typeof (_base = window.getValueCache)[name] === "function" ? _base[name]() : void 0) || null;
};

QuestionView = (function(_super) {
  __extends(QuestionView, _super);

  function QuestionView() {
    this.scrollToTop = __bind(this.scrollToTop, this);
    this.selectMultiple = __bind(this.selectMultiple, this);
    this.render = __bind(this.render, this);
    return QuestionView.__super__.constructor.apply(this, arguments);
  }

  QuestionView.prototype.el = '#content';

  QuestionView.prototype.initialize = function() {
    if (Coconut.resultCollection == null) {
      Coconut.resultCollection = new ResultCollection();
    }
    return this.autoscrollTimer = 0;
  };

  QuestionView.prototype.triggerChangeIn = function(names) {
    var elements, name, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = names.length; _i < _len; _i++) {
      name = names[_i];
      elements = [];
      elements.push(window.questionCache[name].find("input, select, textarea, img"));
      _results.push($(elements).each((function(_this) {
        return function(index, element) {
          var event;
          event = {
            target: element
          };
          return _this.actionOnChange(event);
        };
      })(this)));
    }
    return _results;
  };

  QuestionView.prototype.render = function() {
    var bmidialogcontent, skipperList;
    bmidialogcontent = "<h1>Notice</h1> <p> Patient's BMI  is is <div id= 'bmivalue'></div> <br> the normal BMI range is 20 to 24 </p> <br> <a class='remodal-cancel' >OK</a>";
    this.$el.html("<div class='hoveringMessage' id='messageText'> Saving... </div> <div id='question-view'  class='remodal-bg'> <form> " + (this.toHTMLForm(this.model)) + " </form> </div> <div class='remodal' data-remodal-id='modal'> " + bmidialogcontent + " </div> <div id='round-button'  >UP</div>");
    $(".visitSection").addClass("hiddenSections");
    $(".regVisit-vitalsSection").removeClass("hiddenSections");
    this.updateCache();
    this.updateSkipLogic();
    skipperList = [];
    $(this.model.get("questions")).each((function(_this) {
      return function(index, question) {
        if (question.actionOnChange().match(/skip/i)) {
          skipperList.push(question.safeLabel());
        }
        if ((question.get("action_on_questions_loaded") != null) && question.get("action_on_questions_loaded") !== "") {
          return CoffeeScript["eval"](question.get("action_on_questions_loaded"));
        }
      };
    })(this));
    js2form($('form').get(0), this.result.toJSON());
    this.triggerChangeIn(skipperList);
    $('form').on('focus', 'input[type=number]', function(e) {
      $(this).on('mousewheel.disableScroll', function(e) {
        e.preventDefault();
      });
    });
    return $('form').on('blur', 'input[type=number]', function(e) {
      $(this).off('mousewheel.disableScroll');
    });
  };

  QuestionView.prototype.events = {
    "click #question-view": "closeMenu",
    "click input": "closeMenu",
    "keyup input": "closeMenu",
    "change #question-view input": "onChange",
    "change #question-view select": "onChange",
    "change #question-view textarea": "onChange",
    "click #question-view button:contains(+)": "repeat",
    "click #question-view a:contains(Get current location)": "getLocation",
    "click .next_error": "runValidate",
    "click .validate_one": "onValidateOne",
    "click #round-button": "scrollToTop",
    "click .checkboxLabel": "selectMultiple"
  };

  QuestionView.prototype.selectMultiple = function() {
    var thecheckbox;
    thecheckbox = $(this).find('input');
    return thecheckbox.toggle('checked');
  };

  QuestionView.prototype.scrollToTop = function() {
    return $("html, body").animate({
      scrollTop: $('#top-menu').offset().top
    });
  };

  QuestionView.prototype.runValidate = function() {
    return this.validateAll();
  };

  QuestionView.prototype.closeMenu = function() {
    var burgerbutton, menu;
    menu = $('.main-nav');
    burgerbutton = $('.menuburger');
    menu.removeClass("open");
    menu.css('display', 'none');
    return burgerbutton.removeClass("menuisopen", "slow");
  };

  QuestionView.prototype.onChange = function(event) {
    var $target, eventStamp, messageVisible, targetName;
    $target = $(event.target);
    eventStamp = $target.attr("id");
    if (eventStamp === this.oldStamp && (new Date()).getTime() < this.throttleTime + 1000) {
      return;
    }
    this.throttleTime = (new Date()).getTime();
    this.oldStamp = eventStamp;
    targetName = $target.attr("name");
    if (targetName === "complete") {
      if (this.changedComplete) {
        this.changedComplete = false;
        return;
      }
      this.validateAll();
      Coconut.menuView.update();
      this.save();
      this.updateSkipLogic();
      return this.actionOnChange(event);
    } else {
      this.changedComplete = false;
      messageVisible = window.questionCache[targetName].find(".message").is(":visible");
      return _.delay((function(_this) {
        return function() {
          var wasValid;
          if (!messageVisible) {
            wasValid = _this.validateOne({
              key: targetName,
              autoscroll: false,
              button: "<button type='button' data-name='" + targetName + "' class='validate_one'>Validate</button>"
            });
            _this.save();
            _this.updateSkipLogic();
            _this.actionOnChange(event);
            if (wasValid) {
              return _this.autoscroll(event);
            }
          }
        };
      })(this), 500);
    }
  };

  QuestionView.prototype.onValidateOne = function(event) {
    var $target, name;
    $target = $(event.target);
    name = $(event.target).attr('data-name');
    return this.validateOne({
      key: name,
      autoscroll: true,
      leaveMessage: false,
      button: "<button type='button' data-name='" + name + "' class='validate_one'>Validate</button>"
    });
  };

  QuestionView.prototype.validateAll = function() {
    var isValid, key, questionIsntValid, _i, _len, _ref;
    isValid = true;
    _ref = window.keyCache;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      key = _ref[_i];
      questionIsntValid = !this.validateOne({
        key: key,
        autoscroll: isValid,
        leaveMessage: false
      });
      if (isValid && questionIsntValid) {
        isValid = false;
      }
    }
    this.completeButton(isValid);
    if (isValid) {
      $("[name=complete]").parent().scrollTo();
    }
    if (isValid) {
      $("[name=complete]").scrollTo();
    }
    return isValid;
  };

  QuestionView.prototype.validateOne = function(options) {
    var $message, $question, autoscroll, button, e, key, leaveMessage, message;
    key = options.key || '';
    autoscroll = options.autoscroll || false;
    button = options.button || "<button type='button' class='next_error'>Next Error</button>";
    leaveMessage = options.leaveMessage || false;
    $question = window.questionCache[key];
    $message = $question.find(".message");
    try {
      message = this.isValid(key);
    } catch (_error) {
      e = _error;
      alert("isValid error in " + key + "\n" + e);
      message = "";
    }
    if ($message.is(":visible") && leaveMessage) {
      if (message === "") {
        return true;
      } else {
        return false;
      }
    }
    if (message === "") {
      $message.hide();
      if (autoscroll) {
        this.autoscroll($question);
      }
      return true;
    } else {
      $message.show().html("" + message + " " + button).find("button").button();
      this.scrollToQuestion($question);
      return false;
    }
  };

  QuestionView.prototype.isValid = function(question_id) {
    var error, labelText, question, questionWrapper, required, result, type, validation, validationFunctionResult, value, _ref;
    if (!question_id) {
      return;
    }
    result = [];
    questionWrapper = window.questionCache[question_id];
    if (questionWrapper.hasClass("label")) {
      return "";
    }
    question = $("[name=" + question_id + "]", questionWrapper);
    type = $(questionWrapper.find("input").get(0)).attr("type");
    labelText = type === "radio" ? $("label[for=" + (question.attr("id").split("-")[0]) + "]", questionWrapper).text() || "" : (_ref = $("label[for=" + (question.attr("id")) + "]", questionWrapper)) != null ? _ref.text() : void 0;
    required = questionWrapper.attr("data-required") === "true";
    validation = unescape(questionWrapper.attr("data-validation"));
    if (validation === "undefined") {
      validation = null;
    }
    value = window.getValueCache[question_id]();
    if (!questionWrapper.is(":visible")) {
      return "";
    }
    if (question.find("input").length !== 0 && (type === "checkbox" || type === "radio")) {
      return "";
    }
    if (required && (value === "" || value === null)) {
      result.push("'" + labelText + "' is required.");
    }
    if ((validation != null) && validation !== "") {
      try {
        validationFunctionResult = (CoffeeScript["eval"]("(value) -> " + validation, {
          bare: true
        }))(value);
        if (validationFunctionResult != null) {
          result.push(validationFunctionResult);
        }
      } catch (_error) {
        error = _error;
        if (error === 'invisible reference') {
          return '';
        }
        alert("Validation error for " + question_id + " with value " + value + ": " + error);
      }
    }
    if (result.length !== 0) {
      return result.join("<br>") + "<br>";
    }
    return "";
  };

  QuestionView.prototype.scrollToQuestion = function(question) {
    return this.autoscroll($(question).prev());
  };

  QuestionView.prototype.autoscroll = function(event) {
    var $div, $target, safetyCounter;
    clearTimeout(this.autoscrollTimer);
    if (event.jquery) {
      $div = event;
      window.scrollTargetName = $div.attr("data-question-name") || $div.attr("name");
    } else {
      $target = $(event.target);
      window.scrollTargetName = $target.attr("name");
      $div = window.questionCache[window.scrollTargetName];
    }
    this.$next = $div.next();
    if (!this.$next.is(":visible") && this.$next.length > 0) {
      safetyCounter = 0;
      while (!this.$next.is(":visible") && (safetyCounter += 1) < 100) {
        this.$next = this.$next.next();
      }
    }
    if (this.$next.is(":visible")) {
      if (window.questionCache[window.scrollTargetName].find(".message").is(":visible")) {
        return;
      }
      $(window).on("scroll", (function(_this) {
        return function() {
          $(window).off("scroll");
          return clearTimeout(_this.autoscrollTimer);
        };
      })(this));
      return this.autoscrollTimer = setTimeout((function(_this) {
        return function() {
          $(window).off("scroll");
          return _this.$next.scrollTo().find("input[type=text],input[type=number], textarea").focus();
        };
      })(this), 1000);
    }
  };

  QuestionView.prototype.actionOnChange = function(event) {
    var $divQuestion, $target, code, error, message, name, newFunction, nodeName, value;
    nodeName = $(event.target).get(0).nodeName;
    $target = nodeName === "INPUT" || nodeName === "SELECT" || nodeName === "TEXTAREA" ? $(event.target) : $(event.target).parent().parent().parent().find("input,textarea,select");
    if (!$target.is(":visible")) {
      return;
    }
    name = $target.attr("name");
    $divQuestion = $(".question [data-question-name=" + name + "]");
    code = $divQuestion.attr("data-action_on_change");
    try {
      value = ResultOfQuestion(name);
    } catch (_error) {
      error = _error;
      if (error === "invisible reference") {
        return;
      }
    }
    if (code === "" || (code == null)) {
      return;
    }
    code = "(value) -> " + code;
    try {
      newFunction = CoffeeScript["eval"].apply(this, [code]);
      return newFunction(value);
    } catch (_error) {
      error = _error;
      name = (/function (.{1,})\(/.exec(error.constructor.toString())[1]);
      message = error.message;
      return alert("Action on change error in question " + ($divQuestion.attr('data-question-id') || $divQuestion.attr("id")) + "\n\n" + name + "\n\n" + message);
    }
  };

  QuestionView.prototype.updateSkipLogic = function() {
    var $question, error, message, name, result, skipLogicCode, _ref, _results;
    _ref = window.questionCache;
    _results = [];
    for (name in _ref) {
      $question = _ref[name];
      skipLogicCode = window.skipLogicCache[name];
      if (skipLogicCode === "" || (skipLogicCode == null)) {
        continue;
      }
      try {
        result = eval(skipLogicCode);
      } catch (_error) {
        error = _error;
        if (error === "invisible reference") {
          result = true;
        } else {
          name = (/function (.{1,})\(/.exec(error.constructor.toString())[1]);
          message = error.message;
          alert("Skip logic error in question " + ($question.attr('data-question-id')) + "\n\n" + name + "\n\n" + message);
        }
      }
      if (result) {
        _results.push($question[0].style.display = "none");
      } else {
        _results.push($question[0].style.display = "");
      }
    }
    return _results;
  };

  QuestionView.prototype.save = _.throttle(function() {
    var currentData;
    currentData = $('form').toObject({
      skipEmpty: false
    });
    currentData.lastModifiedAt = moment(new Date()).format(Coconut.config.get("datetime_format"));
    currentData.savedBy = $.cookie('current_user');
    return this.result.save(currentData, {
      success: function(model) {
        $("#messageText").slideDown().fadeOut();
        return Coconut.router.navigate("edit/result/" + model.id, false);
      }
    });
  }, 1000);

  QuestionView.prototype.completeButton = function(value) {
    this.changedComplete = true;
    if ($('[name=complete]').prop("checked") !== value) {
      return $('[name=complete]').click();
    }
  };

  QuestionView.prototype.toHTMLForm = function(questions, groupId) {
    if (questions == null) {
      questions = this.model;
    }
    window.skipLogicCache = {};
    if (questions.length == null) {
      questions = [questions];
    }
    return _.map(questions, (function(_this) {
      return function(question) {
        var html, index, name, newGroupId, option, options, optionsUrl, placeholderText, question_id, repeatable, result, resultOptionsArray, section, specifyHeight, textareaHeight, theOptionsArrayFile, thing;
        if (question.repeatable() === "true") {
          repeatable = "<button>+</button>";
        } else {
          repeatable = "";
        }
        if ((question.type() != null) && (question.label() != null) && question.label() !== "") {
          name = question.safeLabel();
          window.skipLogicCache[name] = question.skipLogic() !== '' ? CoffeeScript.compile(question.skipLogic(), {
            bare: true
          }) : '';
          question_id = question.get("id");
          if (question.repeatable() === "true") {
            name = name + "[0]";
            question_id = question.get("id") + "-0";
          }
          if (groupId != null) {
            name = "group." + groupId + "." + name;
          }
          return "<div " + (question.validation() ? question.validation() ? "data-validation = '" + (escape(question.validation())) + "'" : void 0 : "") + " data-required='" + (question.required()) + "' class='question " + ((typeof question.type === "function" ? question.type() : void 0) || '') + " " + (question.section()) + "' data-question-name='" + name + "' data-question-id='" + question_id + "' data-action_on_change='" + (_.escape(question.actionOnChange())) + "' > " + (!~question.type().indexOf('hidden') ? "<label type='" + (question.type()) + "' for='" + question_id + "'>" + (question.label()) + " <span></span></label>" : void 0) + " <div class='message'></div> " + ((function() {
            var _i, _j, _k, _l, _len, _len1, _len2, _len3, _len4, _len5, _len6, _len7, _m, _n, _o, _p, _ref, _ref1, _ref2, _ref3, _ref4;
            switch (question.type()) {
              case "textarea":
                placeholderText = question.placeholdertext();
                textareaHeight = question.textareaheight();
                if (textareaHeight !== null) {
                  specifyHeight = "style = 'height:" + textareaHeight + "'";
                } else {
                  specifyHeight = "";
                }
                return "<textarea name='" + name + "' type='textarea' id='" + question_id + "' value='" + (_.escape(question.value())) + "' placeholder='" + placeholderText + "' " + specifyHeight + "></textarea>";
              case "select":
                if (this.readonly) {
                  return question.value();
                } else {
                  html = "<select  >";
                  _ref = question.get("select-options").split(/, */);
                  for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
                    option = _ref[index];
                    html += "<option name='" + name + "' id='" + question_id + "-" + index + "' value='" + option + "'>" + option + "</option>";
                  }
                  return html += "</select>";
                }
                break;
              case "multiselect":
                if (this.readonly) {
                  return question.value();
                } else {
                  html = "<ul class='multiSelectList'>";
                  _ref1 = question.get("select-options").split(/, */);
                  for (index = _j = 0, _len1 = _ref1.length; _j < _len1; index = ++_j) {
                    option = _ref1[index];
                    html += "<li><input class = 'largecheckbox' id='" + question_id + "-" + index + "'  name='" + name + "' type='checkbox' value='" + option + "'><label for = '" + question_id + "-" + index + "' class ='checkboxLabel'>" + option + "</label></li>";
                  }
                  return html += "</ul>";
                }
                break;
              case "multiselect-labs":
                if (this.readonly) {
                  return question.value();
                } else {
                  resultOptionsArray = question.labresultoptions().split(/, */);
                  html = "<ul class='multiSelectList'>";
                  _ref2 = question.get("select-options").split(/, */);
                  for (index = _k = 0, _len2 = _ref2.length; _k < _len2; index = ++_k) {
                    option = _ref2[index];
                    html += "<li><input class = 'largecheckbox' id='" + question_id + "-" + index + "'  name='" + name + "' type='checkbox' value='" + option + "'> <label for = '" + question_id + "-" + index + "' class ='checkboxLabel'>" + option + " " + resultOptionsArray[index] + " </label> ";
                  }
                  return html += "</ul>";
                }
                break;
              case "radio":
                if (this.readonly) {
                  return "<input class='radioradio' name='" + name + "' type='text' id='" + question_id + "' value='" + (question.value()) + "'></input>";
                } else {
                  options = question.get("radio-options");
                  return _.map(options.split(/, */), function(option, index) {
                    if (index === 0) {
                      return "<input class='radio' type='radio' name='" + name + "' id='" + question_id + "-" + index + "' value='" + (_.escape(option)) + "' checked ='checked'/> <label class='radio' for='" + question_id + "-" + index + "'>" + option + "</label>";
                    } else {
                      return " <input class='radio' type='radio' name='" + name + "' id='" + question_id + "-" + index + "' value='" + (_.escape(option)) + "'/> <label class='radio' for='" + question_id + "-" + index + "'>" + option + "</label>";
                    }
                  }).join("");
                }
                break;
              case "checkbox":
                if (this.readonly) {
                  return "<input name='" + name + "' type='text' id='" + question_id + "' value='" + (_.escape(question.value())) + "'></input>";
                } else {
                  return "<input style='display:none' name='" + name + "' id='" + question_id + "' type='checkbox' value='true'></input>";
                }
                break;
              case "date":
                if (this.readonly) {
                  return question.value();
                } else {
                  return "<input  type='text' id='datepicker-" + question_id + "' ></input>";
                }
                break;
              case "number":
                if (this.readonly) {
                  return question.value();
                } else {
                  return "<input name='" + name + "' type='number' id='" + question_id + "' value='" + (question.value()) + "'></input>";
                }
                break;
              case "multitag":
                if (this.readonly) {
                  return question.value();
                } else {
                  placeholderText = question.placeholdertext();
                  html = "<select  class='chosen-select' multiple data-placeholder='" + placeholderText + "'>";
                  _ref3 = question.get("multitag-options").split(/, */);
                  for (index = _l = 0, _len3 = _ref3.length; _l < _len3; index = ++_l) {
                    option = _ref3[index];
                    html += "<option name='" + name + "' id='" + question_id + "-" + index + "' value='" + option + "'>" + option + "</option>";
                  }
                  return html += "</select>";
                }
                break;
              case "multitag from file":
                if (this.readonly) {
                  return question.value();
                } else {
                  placeholderText = question.placeholdertext();
                  theOptionsArrayFile = question.get("multitag-options-file");
                  result = [];
                  optionsUrl = "" + theOptionsArrayFile;
                  $.ajax("questionOptions/" + optionsUrl, {
                    async: false,
                    success: function(data, status, xhr) {
                      return result = $.csv.toArray(data);
                    },
                    error: function(xhr, status, err) {
                      return console.log("nah " + err);
                    },
                    complete: function(xhr, status) {}
                  });
                  html = "<select  class='chosen-select' multiple data-placeholder='" + placeholderText + "'>";
                  for (_m = 0, _len4 = result.length; _m < _len4; _m++) {
                    option = result[_m];
                    html += "<option name='" + name + "' id='" + question_id + "-" + index + "' value='" + option + "'>" + option + "</option>";
                  }
                  return html += "</select>";
                }
                break;
              case "multitag from file with groups":
                if (this.readonly) {
                  return question.value();
                } else {
                  placeholderText = question.placeholdertext();
                  theOptionsArrayFile = question.get("multitag-options-file");
                  result = [];
                  optionsUrl = "" + theOptionsArrayFile;
                  $.ajaxSetup({
                    async: false
                  });
                  $.getJSON("questionOptions/" + optionsUrl, function(jsn) {
                    result = jsn.jsonObject;
                  });
                  html = "<select  class='chosen-select' multiple data-placeholder='" + placeholderText + "'>";
                  for (index = _n = 0, _len5 = result.length; _n < _len5; index = ++_n) {
                    section = result[index];
                    html += "<optgroup label  = " + section.name + ">";
                    _ref4 = section.options;
                    for (index = _o = 0, _len6 = _ref4.length; _o < _len6; index = ++_o) {
                      option = _ref4[index];
                      html += "<option value='" + option + "'>" + option + "</option>";
                    }
                    html += "</optgroup>";
                  }
                  return html += "</select>";
                }
                break;
              case "multitag from file with pairs":
                if (this.readonly) {
                  return question.value();
                } else {
                  placeholderText = question.placeholdertext();
                  theOptionsArrayFile = question.get("multitag-options-file");
                  result = [];
                  optionsUrl = "" + theOptionsArrayFile;
                  $.ajaxSetup({
                    async: false
                  });
                  $.getJSON("questionOptions/" + optionsUrl, function(jsn) {
                    result = jsn.jsonObject;
                  });
                  html = "<select  class='chosen-select' multiple data-placeholder='" + placeholderText + "'>";
                  for (index = _p = 0, _len7 = result.length; _p < _len7; index = ++_p) {
                    thing = result[index];
                    html += "<option value = " + thing.code + ">" + thing.name + "-" + thing.code + "</option>";
                  }
                  return html += "</select>";
                }
                break;
              case "location":
                this.watchID = navigator.geolocation.getAccurateCurrentPosition(function() {}, function() {}, function() {}, {
                  desiredAccuracy: 50,
                  maxWait: 60 * 5 * 1000
                });
                return "<a data-question-id='" + question_id + "'>Get current location</a> <label for='" + question_id + "-description'>Location Description</label> <input type='text' name='" + name + "-description' id='" + question_id + "-description'></input> " + (_.map(["latitude", "longitude", "accuracy"], function(field) {
                  return "<label for='" + question_id + "-" + field + "'>" + field + "</label><input readonly='readonly' type='number' name='" + name + "-" + field + "' id='" + question_id + "-" + field + "'></input>";
                }).join("")) + " " + (_.map(["altitude", "altitudeAccuracy", "heading", "timestamp"], function(field) {
                  return "<input type='hidden' name='" + name + "-" + field + "' id='" + question_id + "-" + field + "'></input>";
                }).join(""));
              case "image":
                return "<img style='" + (question.get("image-style")) + "' src='" + (question.get("image-path")) + "'/>";
              case "label":
                return "";
              default:
                return "<input name='" + name + "' id='" + question_id + "' type='" + (question.type()) + "' value='" + (question.value()) + "'></input>";
            }
          }).call(_this)) + " </div> " + repeatable;
        } else {
          newGroupId = question_id;
          if (question.repeatable()) {
            newGroupId = newGroupId + "[0]";
          }
          return ("<div data-group-id='" + question_id + "' class='question group'>") + _this.toHTMLForm(question.questions(), newGroupId) + "</div>" + repeatable;
        }
      };
    })(this)).join("");
  };

  QuestionView.prototype.updateCache = function() {
    var $qC, accessorFunction, inputs, name, question, selects, type, _i, _len, _ref;
    window.questionCache = {};
    window.getValueCache = {};
    window.$questions = $(".question");
    _ref = window.$questions;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      question = _ref[_i];
      name = question.getAttribute("data-question-name");
      if ((name != null) && name !== "") {
        accessorFunction = {};
        window.questionCache[name] = $(question);
        $qC = window.questionCache[name];
        selects = $("select[name=" + name + "]", $qC);
        if (selects.length === 0) {
          inputs = $("input[name=" + name + "]", $qC);
          if (inputs.length !== 0) {
            type = inputs[0].getAttribute("type");
            if (type === "radio") {
              (function(name, $qC) {
                return accessorFunction = function() {
                  return $("input:checked", $qC).safeVal();
                };
              })(name, $qC);
            } else if (type === "checkbox") {
              (function(name, $qC) {
                return accessorFunction = function() {
                  return $("input", $qC).map(function() {
                    return $(this).safeVal();
                  });
                };
              })(name, $qC);
            } else {
              (function(inputs) {
                return accessorFunction = function() {
                  return inputs.safeVal();
                };
              })(inputs);
            }
          } else {
            (function(name, $qC) {
              return accessorFunction = function() {
                return $(".textarea[name=" + name + "]", $qC).safeVal();
              };
            })(name, $qC);
          }
        } else {
          (function(selects) {
            return accessorFunction = function() {
              return selects.safeVal();
            };
          })(selects);
        }
        window.getValueCache[name] = accessorFunction;
      }
    }
    return window.keyCache = _.keys(questionCache);
  };

  QuestionView.prototype.currentKeyExistsInResultsFor = function(question) {
    return Coconut.resultCollection.any((function(_this) {
      return function(result) {
        return _this.result.get(_this.key) === result.get(_this.key) && result.get('question') === question;
      };
    })(this));
  };

  QuestionView.prototype.repeat = function(event) {
    var button, inputElement, name, newIndex, newQuestion, questionID, re, _i, _len, _ref;
    button = $(event.target);
    newQuestion = button.prev(".question").clone();
    questionID = newQuestion.attr("data-group-id");
    if (questionID == null) {
      questionID = "";
    }
    _ref = newQuestion.find("input");
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      inputElement = _ref[_i];
      inputElement = $(inputElement);
      name = inputElement.attr("name");
      re = new RegExp("" + questionID + "\\[(\\d)\\]");
      newIndex = parseInt(_.last(name.match(re))) + 1;
      inputElement.attr("name", name.replace(re, "" + questionID + "[" + newIndex + "]"));
    }
    button.after(newQuestion.add(button.clone()));
    return button.remove();
  };

  QuestionView.prototype.getLocation = function(event) {
    var maxWait, onError, onProgress, onSuccess, question_id, requiredAccuracy, updateFormWithCoordinates;
    requiredAccuracy = 200;
    maxWait = 3 * 60 * 1000;
    question_id = $(event.target).closest("[data-question-id]").attr("data-question-id");
    $("#" + question_id + "-description").val("Retrieving position, please wait.");
    updateFormWithCoordinates = function(geoposition) {
      _.each(geoposition.coords, function(value, key) {
        return $("#" + question_id + "-" + key).val(value);
      });
      $("#" + question_id + "-timestamp").val(moment(geoposition.timestamp).format(Coconut.config.get("datetime_format")));
      return $.getJSON("http://api.geonames.org/findNearbyPlaceNameJSON?lat=" + geoposition.coords.latitude + "&lng=" + geoposition.coords.longitude + "&username=mikeymckay&callback=?", null, (function(_this) {
        return function(result) {
          return $("#" + question_id + "-description").val(parseFloat(result.geonames[0].distance).toFixed(1) + " km from center of " + result.geonames[0].name);
        };
      })(this));
    };
    onSuccess = (function(_this) {
      return function(geoposition) {
        $("label[type=location]").html("Household Location");
        updateFormWithCoordinates(geoposition);
        $("#" + question_id + "-description").val("Success");
        return _this.save();
      };
    })(this);
    onError = function(error) {
      return $("#" + question_id + "-description").val("Error: " + (JSON.stringify(error)));
    };
    onProgress = (function(_this) {
      return function(geoposition) {
        updateFormWithCoordinates(geoposition);
        return $("label[type=location]").html("Household Location<div style='background-color:yellow'>Current accuracy is " + geoposition.coords.accuracy + " meters - must be less than " + requiredAccuracy + " meters. Make sure there are no trees or buildings blocking view to the sky.</div>");
      };
    })(this);
    navigator.geolocation.clearWatch(this.watchID);
    return navigator.geolocation.getAccurateCurrentPosition(onSuccess, onError, onProgress, {
      desiredAccuracy: requiredAccuracy,
      maxWait: maxWait
    });
  };

  return QuestionView;

})(Backbone.View);

(function($) {
  $.fn.scrollTo = function(speed, callback) {
    var e;
    if (speed == null) {
      speed = 500;
    }
    try {
      $('html, body').animate({
        scrollTop: $(this).offset().top + 'px'
      }, speed, null, callback);
    } catch (_error) {
      e = _error;
      console.log("error", e);
      console.log("Scroll error with 'this'", this);
    }
    return this;
  };
  return $.fn.safeVal = function() {
    if (this.is(":visible") || this.parents(".question").filter(function() {
      return !$(this).hasClass("group");
    }).is(":visible")) {
      return $.trim(this.val() || '');
    } else {
      return null;
    }
  };
})($);

//# sourceMappingURL=QuestionView.js.map
