// Generated by CoffeeScript 1.8.0
var AutocompleteFromCode,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

AutocompleteFromCode = (function(_super) {
  __extends(AutocompleteFromCode, _super);

  function AutocompleteFromCode() {
    return AutocompleteFromCode.__super__.constructor.apply(this, arguments);
  }

  AutocompleteFromCode.prototype.getTheAutocompleteList = function(whichList) {
    return console.log(whichList);
  };

  AutocompleteFromCode.prototype.allFacilities = function() {
    console.log("doing stuff for facilities");
    return alert("hi");
  };

  return AutocompleteFromCode;

})(Backbone.Model);

//# sourceMappingURL=AutocompleteFromCode.js.map
