// Generated by CoffeeScript 1.8.0
(function(document) {
  if (document.collection === "result") {
    if (document.ClientID) {
      emit(document.ClientID, null);
    }
    if (document.question === "Client Registration") {
      return emit(document._id, null);
    }
  }
});

//# sourceMappingURL=map.js.map
